### ISSUE TITLE
Don't require enzyme?

### ISSUE THREAD

**Issue by ArtskydJ** [cdlewis/snapshotter#8]
Any thoughts on making this take any ol' object? Right now, it runs everything through `enzyme-to-json`, which I would like to avoid.

I would like this to work:
```js
test('myObject is what I expect', (assert) => {
  const myObject = // non-enzyme object
  compareToSnapshot(assert, myObject , 'myObject')
  assert.end()
})
```

Would you accept a PR?
And if so, what should the API look like, to distinguish between enzyme objects, and non-enzyme objects?
Or is there a way to detect whether it is an enzyme object or not?

**Comment by cdlewis** [comment]
I'm curious what your use-case for this is?

I'm open to it. I think for backwards compatibility it should default to enzyme, but perhaps we could expose a way for you to override that behaviour. E.g. expose a function on the package called something like `.setSnapshotSerializer()`.

**Comment by ArtskydJ** [comment]
My use-case was a large amount of application state that I wanted to snapshot. This lib looked pretty promising, but seems to be enzyme specific.

And actually I've solved the problem by now, so I don't think I'll be making any PRs. Feel free to close this issue, if you want.

**Comment by cdlewis** [comment]
Yeah it's pretty enzyme specific. I think that use case is kinda interesting. I was trying to think of what this provides vs. rolling your own snapshotting. I guess stuff like file management / pretty diffing?

Jest supports something similar where you can call expect(jsonBlob).toMatchSnapshot(). I still think it's a cool idea but like you I don't have a compelling use-case right now.

**Comment by cdlewis** [comment]
Should be fixed :)
